version: '3.6'

services:
  mspatientsapp:
    depends_on:
      - nativappsdb     
    build: 
      context: .
      dockerfile: Dockerfile
    image: mspatients
    container_name: mspatientsapp
    restart: always 
    ports:
      - "${PORT}:${PORT}"      
    environment:       
      PORT: ${PORT}
      PASSWORD: ${PASSWORD}
      USER: ${USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}  
    
  nativappsdb:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    container_name: nativappsdb
    volumes:
      - ./postgres:/var/lib/postgresql/data    

networks:
  default:
    name: nativapps-nw
    external: true
      
  