version: '3'

services:
  mspatientsapp:
      depends_on:
        - nativappsdb
      links:
        - nativappsdb

      build: 
        context: .
        dockerfile: Dockerfile
      image: mspatients
      container_name: mspatientsapp
      restart: always 
      ports:
        - "${PORT}:${PORT}"      
      environment:       
        PORT: ${PORT}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_NAME}
        DB_NAME: ${DB_NAME}
        DB_HOST: localhost
        DB_PORT: ${DB_PORT}      
    
  nativappsdb:
    image: postgres:14.3
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      #POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      #POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    container_name: nativappsdb
    volumes:
      - ./postgres:/var/lib/postgresql/data